### Crear usuario en la base de datos
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "usunom": "Angie Martinez",
    "usuemail": "angie@gmail.com",
    "usupwd": "angie161121@",
    "usudocu": "1137089214",
    "usucel": "4898484894",
    "rolid": 1,
    "tidid": 2
}
