### Crear usuario en la base de datos
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "usunom": "Pepito Perez",
    "usuemail": "pepito@gmail.com",
    "usupwd": "pepito161121@",
    "usudocu": "1137089214",
    "usucel": "4898484894",
    "usufch_nacimiento": "2004-12-20",
    "ceeid": 1,
    "rolid": 1,
    "tidid": 2
}

### Iniciar sesión con correo y contraseña
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "usuemail": "pepito@gmail.com",
    "usupwd": "Json161121@"
}
